/**
 * 通用演示研究图：固定时间戳和 ID 让 UI、截图和算法测试可复现。
 * General demo research graph: fixed timestamps and IDs keep UI, screenshots, and algorithms reproducible.
 */

import type {
  GraphSuggestion,
  ProjectState,
  ResearchEdge,
  ResearchNode,
} from "./research-types";

const now = "2026-07-26T02:00:00.000Z";
const human = { origin: "human" as const, actorId: "local-researcher" };
const ai = {
  origin: "ai" as const,
  modelId: "research-extractor-demo",
  promptVersion: "extract-v0.1",
};

const node = (
  id: string,
  type: ResearchNode["type"],
  title: string,
  body: string,
  tags: string[],
  evidenceIds: string[] = [],
  status: ResearchNode["status"] = "confirmed",
): ResearchNode => ({
  id,
  type,
  title,
  body,
  tags,
  status,
  evidenceIds,
  data: {},
  provenance: human,
  createdAt: now,
  updatedAt: now,
});

const edge = (
  id: string,
  source: string,
  target: string,
  type: ResearchEdge["type"],
  evidenceIds: string[] = [],
): ResearchEdge => ({
  id,
  source,
  target,
  type,
  directed: true,
  polarity: type === "contradicts" ? "negative" : "positive",
  confidence: evidenceIds.length ? 0.89 : 0.72,
  conditions: [],
  evidenceIds,
  provenance: human,
});

const positions: Record<string, [number, number]> = {
  q1: [40, 250],
  d1: [40, 480],
  m1: [330, 120],
  m2: [330, 310],
  m3: [330, 500],
  v1: [660, 80],
  v2: [660, 250],
  v3: [660, 430],
  h1: [660, 610],
  x1: [980, 170],
  r1: [980, 360],
  r2: [980, 540],
  p1: [1280, 260],
  e1: [1280, 470],
};

export const initialProject: ProjectState = {
  schemaVersion: 1,
  id: "project-transformer-ablation",
  title: "Long-context Transformer ablation",
  discipline: "Neural Networks",
  updatedAt: now,
  revision: 18,
  nodes: [
    node(
      "q1",
      "question",
      "What enables long-context generalization?",
      "Trace which architectural components are necessary for stable accuracy beyond the training context window.",
      ["long-context", "ablation"],
      ["ev1"],
    ),
    node("d1", "dataset", "LongBench subset", "A controlled long-context evaluation split.", ["evaluation"], ["ev3"]),
    node("m1", "method", "Token embedding", "Maps discrete input tokens into the model representation space.", ["encoder"]),
    node("m2", "method", "Rotary positional encoding", "Injects relative position information before attention.", ["position", "RoPE"], ["ev1"]),
    node("m3", "method", "Multi-head attention", "Routes content across token positions.", ["attention"], ["ev2"]),
    node("v1", "variable", "Context length", "Number of tokens available to the model at evaluation time.", ["independent"]),
    node("v2", "variable", "Training steps", "Optimization budget held constant across ablation runs.", ["control"]),
    node("v3", "variable", "Parameter count", "Effective trainable parameter count after the intervention.", ["control"]),
    node("h1", "hypothesis", "Position signal matters more beyond 8k", "Removing RoPE should disproportionately hurt long-context accuracy.", ["testable"], ["ev1"]),
    node("x1", "experiment", "Matched-compute ablation", "Compare baseline and no-RoPE variants with matched data order, steps and seeds.", ["planned"]),
    node("r1", "metric", "Long-context accuracy", "Exact-match accuracy for examples requiring more than 8k tokens.", ["primary"], ["ev3"]),
    node("r2", "metric", "Short-context accuracy", "Accuracy below 2k tokens, used as a distribution-shift check.", ["diagnostic"]),
    node("p1", "result", "Expected selective degradation", "Long-context accuracy decreases more than short-context accuracy.", ["expected"], [], "draft"),
    node("e1", "evidence", "Ablation table, page 7", "The paper reports a 6.4 point drop at 16k context.", ["paper-evidence"], ["ev1"]),
  ],
  edges: [
    edge("e-q-m1", "q1", "m1", "depends_on"),
    edge("e-q-h1", "q1", "h1", "depends_on"),
    edge("e-m1-m2", "m1", "m2", "depends_on"),
    edge("e-m2-m3", "m2", "m3", "depends_on", ["ev1"]),
    edge("e-v1-m2", "v1", "m2", "moderates"),
    edge("e-m3-x1", "m3", "x1", "uses"),
    edge("e-h1-x1", "h1", "x1", "derived_from"),
    edge("e-v2-x1", "v2", "x1", "controls"),
    edge("e-v3-x1", "v3", "x1", "controls"),
    edge("e-d1-x1", "d1", "x1", "uses"),
    edge("e-x1-r1", "x1", "r1", "measures"),
    edge("e-x1-r2", "x1", "r2", "measures"),
    edge("e-r1-p1", "r1", "p1", "supports"),
    edge("e-r2-p1", "r2", "p1", "supports"),
    edge("e-e1-h1", "e1", "h1", "supports", ["ev1"]),
  ],
  evidence: [
    {
      id: "ev1",
      sourceType: "paper",
      sourceId: "paper-rope-2024",
      title: "Extending context windows with rotary embeddings",
      authors: "Chen, Rao & Li",
      year: 2024,
      doi: "10.0000/example.rope",
      url: "https://example.org/papers/rope",
      locator: {
        page: 7,
        section: "4.2 Ablations",
        quote: "Removing the rotary signal causes the largest degradation beyond 8k tokens.",
      },
      status: "verified",
      provenance: human,
    },
    {
      id: "ev2",
      sourceType: "paper",
      sourceId: "paper-attention-2017",
      title: "Attention mechanisms for sequence modeling",
      authors: "Vaswani et al.",
      year: 2017,
      url: "https://arxiv.org/abs/1706.03762",
      locator: { page: 4, section: "3.2 Attention" },
      status: "verified",
      provenance: human,
    },
    {
      id: "ev3",
      sourceType: "dataset",
      sourceId: "longbench-subset-v2",
      title: "LongBench evaluation protocol",
      year: 2025,
      locator: { section: "Filtered evaluation split" },
      status: "verified",
      provenance: human,
    },
  ],
  placements: Object.entries(positions).map(([nodeId, [x, y]]) => ({
    id: `placement-${nodeId}`,
    viewId: "view-main",
    nodeId,
    x,
    y,
    width: 230,
    height: 116,
  })),
  scenarios: [
    {
      id: "scenario-no-rope",
      name: "No positional encoding",
      disabledNodeIds: ["m2"],
      disabledEdgeIds: [],
      nodeOverrides: {},
      edgeOverrides: {},
      parameters: { seeds: [13, 21, 34], matchedCompute: true },
      hypothesis: "Long-context accuracy will decrease while short-context accuracy remains mostly stable.",
      expectedEffect: "Primary metric −6% to −10%",
      createdAt: now,
    },
    {
      id: "scenario-no-long-data",
      name: "No long-context examples",
      disabledNodeIds: ["d1"],
      disabledEdgeIds: [],
      nodeOverrides: {},
      edgeOverrides: {},
      parameters: { trainingSteps: "unchanged" },
      hypothesis: "The model will fail to generalize to context lengths absent during training.",
      expectedEffect: "Both stability and accuracy decrease",
      createdAt: now,
    },
  ],
  activity: [
    { id: "a3", label: "Verified evidence on RoPE", origin: "human", createdAt: "2026-07-26T02:43:00Z" },
    { id: "a2", label: "Created scenario “No positional encoding”", origin: "human", createdAt: "2026-07-26T02:37:00Z" },
    { id: "a1", label: "Imported method structure", origin: "ai", createdAt: "2026-07-26T02:31:00Z" },
  ],
};

export const initialSuggestions: GraphSuggestion[] = [
  {
    id: "suggestion-control-seed",
    kind: "node",
    title: "Add random seed as a control",
    description: "Random seed is held constant in the cited ablation protocol but is not yet represented in the graph.",
    confidence: 0.93,
    rationale: "A fair ablation needs identical initialization and data order.",
    evidenceLabel: "Page 7 · Ablations · verified quote",
    status: "proposed",
    node: {
      type: "variable",
      title: "Random seed",
      body: "Initialization and data-order seed held constant across scenarios.",
      tags: ["control", "reproducibility"],
      status: "draft",
      evidenceIds: ["ev1"],
      data: {},
      provenance: ai,
    },
  },
  {
    id: "suggestion-edge",
    kind: "edge",
    title: "Connect RoPE to long-context accuracy",
    description: "The evidence supports a direct measured relationship between the position signal and the primary metric.",
    confidence: 0.86,
    rationale: "This keeps the paper claim separate from the model’s structural dependency edge.",
    evidenceLabel: "Page 7 · Table 3",
    status: "proposed",
    edge: {
      type: "supports",
      source: "m2",
      target: "r1",
      directed: true,
      polarity: "positive",
      confidence: 0.86,
      conditions: ["context_length > 8k"],
      evidenceIds: ["ev1"],
      note: "Candidate edge extracted from ablation table.",
      provenance: ai,
    },
  },
  {
    id: "suggestion-result",
    kind: "node",
    title: "Track calibration drift",
    description: "The discussion section names calibration as a secondary risk after removing position information.",
    confidence: 0.72,
    rationale: "Adding this as a draft metric would make the scenario evaluation more complete.",
    evidenceLabel: "Page 9 · Limitations · candidate",
    status: "proposed",
    node: {
      type: "metric",
      title: "Calibration error",
      body: "Expected calibration error measured separately for short and long contexts.",
      tags: ["secondary", "calibration"],
      status: "draft",
      evidenceIds: [],
      data: {},
      provenance: ai,
    },
  },
];
